### ISSUE TITLE
Unclear current_user_stripee function

### ISSUE THREAD

**Issue by dyatlov** [felixog/coursify#3]
See https://github.com/felixog/coursify/blob/master/coursify/app/controllers/pages_controller.rb#L114

What the purpose of the function?
As I understood it returns price which a user should pay upon registration.

Why it depend on amount of registered students?

Why it uses such uneffective code? It seems like a rails newbie written this.

you wrote this:

``` ruby
s = StudentUser.all
count = s.size
```

whereas a correct way would be to write it in such way:

``` ruby
count = StudentUser.count
```

This way it doesnt fetch hundreds of records from database but just calculates count and returns a result.

**Comment by felixog** [comment]
So I can increase the price after every order, without creating another table for orders just yet. 

I know I have a lot of refactoring to do, I'll get on it once I get to a laptop, before I start adding new features. 

—

**Comment by bolak** [comment]
Dyatlov that's not Rails code, that's straight up Ruby...

Calling people Rails newbies is not constructive.

**Comment by dyatlov** [comment]
@seanbolak what's wrong with word 'newbie'?
I see that the code is written in a bad style and in a bad way so from there come all my conclusions.
I wouldn't let such code go to any of my projects.

**Comment by felixog** [comment]
Thanks guys, that issue has been fixed now (see my last push).

The "stripee" function was a temporary solution (hence the bad name). I forgot to fix it.
